### ISSUE TITLE
Your specs are failing

### ISSUE THREAD

**Issue by MadBomber** [adhocteam/fml#14]
Since you no longer publish this gem through rubygems.org and since it has not had any attention in a few years and since its has failing specs I'm assuming that it has been abandoned.  Am I wrong?

**Comment by llimllib** [comment]
@MadBomber you are not wrong! If you want to fix it and file a PR I will happily accept it though :)

**Comment by llimllib** [comment]
Nevermind, it was an easy fix: https://github.com/adhocteam/fml/commit/da495274e6712c2df5c06f5f8c8a2aec66f847fa

Thanks for the report and I would love to hear about how you're using FML!
